# Generated by Django 5.0.1 on 2024-02-04 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='add_tim',
            new_name='add_time',
        ),
        migrations.AlterField(
            model_name='recipe',
            name='cook',
            field=models.CharField(max_length=50),
        ),
    ]
