# Generated by Django 5.0.1 on 2024-02-04 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_rename_add_tim_recipe_add_time_alter_recipe_cook'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cookuser',
            name='address',
        ),
    ]
