# Generated by Django 5.0.1 on 2024-02-04 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_remove_cookuser_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='add_time',
            new_name='add_date',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='name',
            new_name='title',
        ),
    ]
