# Generated by Django 5.0.1 on 2024-02-05 19:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_rename_add_time_recipe_add_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cookuser',
            name='recipes',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='recipes.recipe'),
        ),
    ]
