# Generated by Django 5.0.1 on 2024-02-05 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_cookuser_recipes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cookuser',
            name='recipes',
        ),
    ]
