# Generated by Django 5.0.1 on 2024-02-05 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_images_alter_recipe_time_to_cook'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='time_to_cook',
            field=models.TimeField(default='0:00'),
        ),
    ]
