# Generated by Django 5.0.1 on 2024-02-05 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_alter_recipe_time_to_cook'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='cook',
            new_name='author',
        ),
    ]
